/*****************************************************************************
 *
 * NXP Confidential Proprietary
 *
 * Copyright (c) 2014-2016 Freescale Semiconductor
 * Copyright 2017 NXP
 * All Rights Reserved
 *
 ******************************************************************************
 *
 * THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
 * IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/
#ifndef APU_FAST_GRAPH_NAMES_H
#define APU_FAST_GRAPH_NAMES_H

#include <common_stringify_macros.h>

#define FAST9_GR_ID APU_FAST
#define FAST9_GR_STR XSTR(FAST9_GR_ID)

#define FAST9_NMS_GR_ID APU_FAST_NMS
#define FAST9_NMS_GR_STR XSTR(FAST9_NMS_GR_ID)

#define FAST9_GR_IN_IMG "FAST_GR_IN_IMG"
#define FAST9_GR_IN_THR "FAST_GR_IN_THR"
#define FAST9_GR_OUT "FAST_GR_OUT_IMG"

#endif /* APUFASTGRAPH_HPP */
