##############################################################################
#
# NXP Confidential Proprietary
#
# Copyright 2018 NXP;
# All Rights Reserved
#
##############################################################################
#
# THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
# IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
# THE POSSIBILITY OF SUCH DAMAGE.
#
##############################################################################
#
#  CONTENT:
#    Setting the default arm/aarch64 cross compilers prefix: 3rd-party libraries
#
#  AUTHOR
#    Mihail Marian Nistor
#
#  LANGUAGE
#    bash script
#
##############################################################################
# Do not edit this file!
##############################################################################
#!/bin/bash
if [ -z "$CROSS_COMPILE_M0_ELF" ]; then
  export CROSS_COMPILE_M0_ELF=arm-none-eabi-
  echo "Setting CROSS_COMPILE_M0_ELF to ${CROSS_COMPILE_M0_ELF}"
fi
if [ -z "$CROSS_COMPILE_AARCH64_ELF" ]; then
  export CROSS_COMPILE_AARCH64_ELF=aarch64-none-elf-
  echo "Setting CROSS_COMPILE_AARCH64_ELF to ${CROSS_COMPILE_AARCH64_ELF}"
fi
if [ -z "$CROSS_COMPILE" ]; then
  export CROSS_COMPILE=aarch64-linux-gnu-
  echo "Setting CROSS_COMPILE to ${CROSS_COMPILE}"
fi
