/*****************************************************************************
* 
* NXP Confidential Proprietary
*
* Copyright (c) 2014-2016 Freescale Semiconductor
* Copyright 2017 NXP 
* All Rights Reserved
*
******************************************************************************
*
* THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
* IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
* OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
* IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
* INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
* SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
* IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
* THE POSSIBILITY OF SUCH DAMAGE.
*
****************************************************************************/
#ifndef  HISTOGRAMEQUALIZATIONGRAPHNAMES_H
#define  HISTOGRAMEQUALIZATIONGRAPHNAMES_H

#include "common_stringify_macros.h"

#define HISTO_EQU_PI  HISTOGRAM_EQUALIZATION
#define HISTO_EQU_GN  XSTR(HISTO_EQU_PI)

#define HISTO_EQU_IN_IMG    "INPUT_0"
#define HISTO_EQU_OUT_IMG    "OUTPUT_0"
#define HISTO_EQU_NUM_PIXELS  "NUM_PIXELS"
#define HISTO_EQU_HISTO      "IMAGE_HISTOGRAM"

#endif /* HISTOGRAMEQUALIZATIONGRAPHNAMES_H */
